[versions]
agp = "8.13.0"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.27" # The correct KSP version for Kotlin 2.0.21

# AndroidX Libraries
coreKtx = "1.16.0"
appcompat = "1.7.0"
constraintLayout = "2.2.1"
constraintCompose = "1.0.1"
recyclerview = "1.4.0"
activityCompose = "1.11.0"
lifecycle = "2.8.3"
lifecycleRuntimeKtx = "2.8.3"

# Third-party Libraries
glide = "4.16.0"
glideCompose = "1.0.0-beta01"

room = "2.6.1"
retrofit = "2.9.0"
okhttp = "4.12.0"
kotlinxCoroutines = "1.8.1"
koin = "3.5.6"

# Testing Libraries
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
mockito = "5.4.0"

# Compose
composeBom = "2024.06.00"
navigationCompose = "2.9.4"
coilCompose = "2.7.0"
material3 = "1.3.2"

#paging
pagingVersion = "3.4.1"

#data store
dataStore = "1.2.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintCompose" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }

# Retrofit + OkHttp
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }

# Lifecycle
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

# Koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }


# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
#androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }
glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glideCompose" }


#paging
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingVersion" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingVersion" }

#data store
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }
datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "dataStore" }


# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
mockito = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
android-library = { id = "com.android.library", version.ref = "agp" }

